### ISSUE TITLE
improvement: switch to nyc for coverage

### ISSUE THREAD

**Issue by revelt** [shinnn/array-includes-all#1]
Hi

I just tapped this library and while checking its contents I noticed it's using `istanbul`, not `nyc` way to set up coverage calculation.

* Is there a reason for this? It looks like `nyc` setup is shorter.
* Out of curiosity, what do you think of switching to `ava`?

Feel free to close this if it is not an issue for you.

thank you.

**Comment by shinnn** [comment]
Thanks for the suggestion, but I prefer the smaller ones.

```
$ time npm i ava nyc

real	0m58.092s
user	0m24.603s
sys	0m7.465s

$ du -sh node_modules
 56M	node_modules
```

```
$ time npm i tape istanbul

real	0m10.957s
user	0m4.675s
sys	0m0.938s

$ du -sh node_modules
 10M	node_modules
```

**Comment by revelt** [comment]
Aha! Interesting..
